exclude_paths:
  - '**.md'
  - '**.yml'
  - 'docs/**'
  - 'dockers/**'
  - 'makefiles/**'
  - 'scripts/**'
  - 'prototype/**'
  - 'pgtbl/manage.py'
  - 'pgtbl/tbl/**'
  - 'pgtbl/**/tests/**'
  - 'pgtbl/**/migrations/**'
  - 'pgtbl/**/static/**'
  - 'pgtbl/**/templates/**'
  - 'pgtbl/**/fixtures/**'
  - 'pgtbl/**/apps.py'
  - 'pgtbl/**/__init__.py'
