exclude_paths:
  - 'docs/**'
  - 'images/**'
  - 'makefiles/**'
  - 'scripts/**'
  - 'pgtbl/manage.py'
  - 'pgtbl/**/settings.py'
  - 'pgtbl/**/tests/**'
  - 'pgtbl/**/migrations/**'
  - 'pgtbl/**/static/**'
  - 'pgtbl/**/templates/**'
  - 'pgtbl/**/__init__.py'
