sudo: required
language: python

# Specify the version of python
python:
  - "3.5"

# Use docker to deploy
service:
  - docker

# Specify the docker-compose version to deploy
env:
  - DOCKER_COMPOSE_VERSION=1.15.0

# Install docker dependencies
before_script:
  - docker-compose -f docker-compose.local.yml up -d

# Script project dependencies
script:
  - docker exec tbl-local coverage run --source="." pgtbl/manage.py test pgtbl
  - docker exec tbl-local coverage report -m
  - docker exec tbl-local coverage xml
  - docker exec tbl-local python-codacy-coverage -r coverage.xml

deploy:
  # deploy to staging enviroment
  - provider: script
    script: bash scripts/homolog-deploy.sh
    skip_cleanup: true
    on:
      branch: dev

  # deploy to production enviroment
  - provider: script
    script: bash scripts/production-deploy.sh
    skip_cleanup: true
    on:
      branch: master
