sudo: required
language: python

# Specify the version of python
python:
  - "3.5"

# Specify branchs that travis will monitor
branches:
  only:
    - master
    - devel

# Use docker to deploy
service:
  - docker

# Specify the docker-compose version to deploy
env:
  - DOCKER_COMPOSE_VERSION=1.15.0

# Install docker dependencies
before_script:
  - docker-compose up -d

# Script project dependencies
script:
  - docker exec tbl-local make test

deploy:
  # deploy to staging enviroment
  - provider: script
    script: bash staging-deploy.sh
    on:
      branch: develop

  # deploy to production enviroment
  - provider: script
    script: bash production-deploy.sh
    on:
      branch: master
