sudo: required
language: python

# Specify the version of python
python:
  - "3.5"

# Use docker to deploy
service:
  - docker

# Specify the docker-compose version to deploy
env:
  - DOCKER_COMPOSE_VERSION=1.15.0

# Install docker dependencies
before_script:
  - docker-compose -f docker-compose.test.yml up --build -d

# Script project dependencies
script:
  - docker exec pgtbl-test coverage run --source="." pgtbl/manage.py test pgtbl
  - docker exec pgtbl-test coverage report -m
  - docker exec pgtbl-test coverage xml
  - docker exec pgtbl-test python-codacy-coverage -r coverage.xml

deploy:
  # deploy to production enviroment
  - provider: script
    script: bash scripts/production.sh
    skip_cleanup: true
    on:
      branch: master
