sudo: required
language: python

# Specify the version of python
python:
  - "3.5"

# Specify branchs that travis will monitor
branches:
  only:
    - master
    - devel

# Use docker to deploy
service:
  - docker

# Specify the docker-compose version to deploy
env:
  - DOCKER_COMPOSE_VERSION=1.17.1

# Script project dependencies
script:
  - docker-compose -f docker-compose.test.yml up

deploy:
  # deploy to staging enviroment
  - provider: script
    script: bash staging-deploy.sh
    on:
      branch: develop

  # deploy to production enviroment
  - provider: script
    script: bash production-deploy.sh
    on:
      branch: master
