version: '3'
services:
  pgtbl-test:
    image: victorhad/tbl:test
    container_name: pgtbl-test
    build:
      context: .
      dockerfile: ./dockers/test/Dockerfile
    environment:
      - CODACY_PROJECT_TOKEN=2856565478ce4400a4cd4731950bfb89
    ports:
      - "8000:8080"