version: '3'
services:
  # NGINX server
  tbl-nginx:
    image: victorhad/tbl:nginx
    container_name: tbl-server
    ports:
      - "8000:8080"
    depends_on:
      - tbl

  # TBL production app
  tbl:
    image: victorhad/tbl:latest
    container_name: tbl
    depends_on:
      - db

  # Postgresql database
  db:
    image: postgres:latest
    container_name: tbl_db
