version: '3'
services:
  # Postgresql database
  db:
    image: postgres:latest
    container_name: tbl_db

  # TBL app
  tbl:
    image: victorhad/tbl:latest
    container_name: tbl
    volumes:
      - .:/software
    ports:
      - "8000:8000"
    depends_on:
      - db
