version: '3'
services:
  nginx:
    image: victorhad/tbl:nginx
    container_name: pgtbl-nginx
    build:
      context: .
      dockerfile: ./dockers/nginx/Dockerfile
    ports:
      - "443:8000"
      - "80:80"
    volumes:
      - ./.ignore/nginx:/var/log/nginx
    depends_on:
      - pgtbl

  pgtbl:
    image: victorhad/pgtbl:latest
    container_name: pgtbl
    build:
      context: .
      dockerfile: ./dockers/production/Dockerfile
    environment:
      - POSTGRES_NAME=pgtbl_db
      - POSTGRES_USER=pgtbl
      - POSTGRES_PASSWORD=pgtbl
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: "./dockers/production/prod.sh"
    volumes:
      - .:/home/pgtbl/
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: pgtbl-db
    environment:
      - POSTGRES_DB=pgtbl_db
      - POSTGRES_USER=pgtbl
      - POSTGRES_PASSWORD=pgtbl
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
